# Generated by Django 6.0.1 on 2026-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="mrp",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
