# Generated by Django 4.2.27 on 2026-01-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_image_product_mrp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
